from PyQt5 import QtWidgets,QtCore
import sys
app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QWidget()
window.setWindowFlags(QtCore.Qt.Window|QtCore.Qt.WindowStaysOnTopHint)

window.setWindowTitle('заголовок')
window.resize(400,100)
window.resize(QtCore.QSize(400,100))
window.setGeometry(100,100,100,70)
window.setGeometry(QtCore.QRect(100,100,100,70))
# window.setFixedSize(200,70)
# window.setFixedWidth()
# window.setFixedHeight()
# window.setMinimumSize()
# window.setMinimumHeight()
# window.setMaximumSize()
# window.setMinimumSize()
# window.setMaximumHeight()
# window.seMaximumWidth()
# window.adjustSize()
# window.setVisible(False)

# rect = window.rect()
# rect = window.geometry()
# rect = window.frameGeometry().height()
# print(rect)
window.show()
sys.exit(app.exec_())
