# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# Автоматически сгенерированный файл
# pyuic5 untitled.ui -o ui_myForm.py в терминале

class Ui_MyForm(object):
    def setupUi(self, MyForm):
        MyForm.setObjectName("MyForm")
        MyForm.resize(387, 140)
        self.label = QtWidgets.QLabel(MyForm)
        self.label.setGeometry(QtCore.QRect(120, 10, 121, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.button = QtWidgets.QPushButton(MyForm)
        self.button.setGeometry(QtCore.QRect(140, 70, 81, 31))
        self.button.setObjectName("button")

        self.retranslateUi(MyForm)
        QtCore.QMetaObject.connectSlotsByName(MyForm)

    def retranslateUi(self, MyForm):
        _translate = QtCore.QCoreApplication.translate
        MyForm.setWindowTitle(_translate("MyForm", "My First Window"))
        self.label.setText(_translate("MyForm", "Новый текст"))
        self.button.setText(_translate("MyForm", "Кнопка"))
